version: '3'

services:
  strapi-app:
    image: ghcr.io/tokileecy/strapi-notes-strapi-app:v0.3.3
    user: '1000:1000'
    container_name: strapi-app
    restart: unless-stopped
    environment:
      - NODE_OPTIONS=--max_old_space_size=2048
      - NODE_ENV=${APP_ENV:-development}
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=${DATABASE_NAME:-strapi}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=${DATABASE_USERNAME:-strapi}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-strapi}
      - APP_KEYS=${APP_KEYS:-someSecret,anotherSecret}
      - JWT_SECRET=${JWT_SECRET:-JWT_SECRET}
      - API_TOKEN_SALT=${API_TOKEN_SALT:-API_TOKEN_SALT}
    command: >
      /bin/sh -c "
        if [ ${APP_ENV:-development} = \"production\" ]; then yarn build && yarn start; else yarn dev; fi
      "
    ports:
      - "${STRAPI_PORT:-1337}:1337"
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-strapi}
      - POSTGRES_USER=${DATABASE_USERNAME:-strapi}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-strapi}
    volumes:
      - ${DATABASE_VOLUME:-./dbs/postgres}:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
  next-app:
    image: ghcr.io/tokileecy/strapi-notes-next-app:v0.3.3
    user: '1000:1000'
    environment:
      - NODE_ENV=${APP_ENV:-development}
      - SERVER_STRAPI_URL=http://strapi-app:1337/
      - PUBLIC_STRAPI_URL=${PUBLIC_STRAPI_URL:-http://127.0.0.1:1337}
      - APP_ENV=${APP_ENV:-development}
    command: >
      /bin/sh -c "
        if [ ${APP_ENV:-development} = \"production\" ]; then yarn build && yarn start; else yarn dev; fi
      "
    depends_on:
      - strapi-app
    ports:
      - "${NEXT_PORT:-3000}:3000"