version: '3'

services:
  strapi:
    build:
      context: ./docker/strapi
      args:
        NODE_VERSION: 16
        STRAPI_VERSION: 4.1.2
      dockerfile: Dockerfile
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./strapi:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres
  postgres:
    image: postgres
    env_file: .env
    container_name: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
  blog:
    build:
      context: ./docker/nextjs
      args:
        NODE_VERSION: 16
      dockerfile: Dockerfile
    container_name: blog
    ports:
      - '3000:3000'
    volumes:
      - ./blog:/srv/app